"""Implementação do experimento de reprodução em treinamento federado."""

from .model_loading import (
    BASE_MODEL_ID,
    BASE_MODEL_REVISION,
    BASE_RESULT_VARIANT,
    DEFAULT_MODEL_CACHE,
    EXPECTED_PARAMETER_COUNT,
    EXPECTED_TOKENIZER_FINGERPRINT,
    MODEL_ARTIFACT_SCHEMA_VERSION,
    MODEL_LOADING_SCHEMA_VERSION,
    HuggingFaceModelSpec,
    LoadedModelBundle,
    LocalArtifactModelSpec,
    ModelArtifactError,
    ModelConfigurationError,
    ModelDependencyError,
    ModelLoadError,
    ModelProvenance,
    load_model_bundle,
    parse_model_spec,
    prepare_huggingface_model,
    validate_local_artifact,
)

__all__ = [
    "BASE_MODEL_ID",
    "BASE_MODEL_REVISION",
    "BASE_RESULT_VARIANT",
    "DEFAULT_MODEL_CACHE",
    "EXPECTED_PARAMETER_COUNT",
    "EXPECTED_TOKENIZER_FINGERPRINT",
    "HuggingFaceModelSpec",
    "LoadedModelBundle",
    "LocalArtifactModelSpec",
    "MODEL_ARTIFACT_SCHEMA_VERSION",
    "MODEL_LOADING_SCHEMA_VERSION",
    "ModelArtifactError",
    "ModelConfigurationError",
    "ModelDependencyError",
    "ModelLoadError",
    "ModelProvenance",
    "load_model_bundle",
    "parse_model_spec",
    "prepare_huggingface_model",
    "validate_local_artifact",
]
